(* generated by dune *)

(** @canonical Gsl.Blas *)
module Blas = Gsl__Blas

(** @canonical Gsl.Blas_flat *)
module Blas_flat = Gsl__Blas_flat

(** @canonical Gsl.Blas_gen *)
module Blas_gen = Gsl__Blas_gen

(** @canonical Gsl.Bspline *)
module Bspline = Gsl__Bspline

(** @canonical Gsl.Cdf *)
module Cdf = Gsl__Cdf

(** @canonical Gsl.Cheb *)
module Cheb = Gsl__Cheb

(** @canonical Gsl.Combi *)
module Combi = Gsl__Combi

(** @canonical Gsl.Const *)
module Const = Gsl__Const

(** @canonical Gsl.Deriv *)
module Deriv = Gsl__Deriv

(** @canonical Gsl.Eigen *)
module Eigen = Gsl__Eigen

(** @canonical Gsl.Error *)
module Error = Gsl__Error

(** @canonical Gsl.Fft *)
module Fft = Gsl__Fft

(** @canonical Gsl.Fit *)
module Fit = Gsl__Fit

(** @canonical Gsl.Fun *)
module Fun = Gsl__Fun

(** @canonical Gsl.Gsl_complex *)
module Gsl_complex = Gsl__Gsl_complex

(** @canonical Gsl.Gsl_sort *)
module Gsl_sort = Gsl__Gsl_sort

(** @canonical Gsl.Histo *)
module Histo = Gsl__Histo

(** @canonical Gsl.Ieee *)
module Ieee = Gsl__Ieee

(** @canonical Gsl.Integration *)
module Integration = Gsl__Integration

(** @canonical Gsl.Interp *)
module Interp = Gsl__Interp

(** @canonical Gsl.Linalg *)
module Linalg = Gsl__Linalg

(** @canonical Gsl.Math *)
module Math = Gsl__Math

(** @canonical Gsl.Matrix *)
module Matrix = Gsl__Matrix

(** @canonical Gsl.Matrix_complex *)
module Matrix_complex = Gsl__Matrix_complex

(** @canonical Gsl.Matrix_complex_flat *)
module Matrix_complex_flat = Gsl__Matrix_complex_flat

(** @canonical Gsl.Matrix_flat *)
module Matrix_flat = Gsl__Matrix_flat

(** @canonical Gsl.Min *)
module Min = Gsl__Min

(** @canonical Gsl.Misc *)
module Misc = Gsl__Misc

(** @canonical Gsl.Monte *)
module Monte = Gsl__Monte

(** @canonical Gsl.Multifit *)
module Multifit = Gsl__Multifit

(** @canonical Gsl.Multifit_nlin *)
module Multifit_nlin = Gsl__Multifit_nlin

(** @canonical Gsl.Multimin *)
module Multimin = Gsl__Multimin

(** @canonical Gsl.Multiroot *)
module Multiroot = Gsl__Multiroot

(** @canonical Gsl.Odeiv *)
module Odeiv = Gsl__Odeiv

(** @canonical Gsl.Permut *)
module Permut = Gsl__Permut

(** @canonical Gsl.Poly *)
module Poly = Gsl__Poly

(** @canonical Gsl.Qrng *)
module Qrng = Gsl__Qrng

(** @canonical Gsl.Randist *)
module Randist = Gsl__Randist

(** @canonical Gsl.Rng *)
module Rng = Gsl__Rng

(** @canonical Gsl.Root *)
module Root = Gsl__Root

(** @canonical Gsl.Sf *)
module Sf = Gsl__Sf

(** @canonical Gsl.Siman *)
module Siman = Gsl__Siman

(** @canonical Gsl.Stats *)
module Stats = Gsl__Stats

(** @canonical Gsl.Sum *)
module Sum = Gsl__Sum

(** @canonical Gsl.Vectmat *)
module Vectmat = Gsl__Vectmat

(** @canonical Gsl.Vector *)
module Vector = Gsl__Vector

(** @canonical Gsl.Vector_complex *)
module Vector_complex = Gsl__Vector_complex

(** @canonical Gsl.Vector_complex_flat *)
module Vector_complex_flat = Gsl__Vector_complex_flat

(** @canonical Gsl.Vector_flat *)
module Vector_flat = Gsl__Vector_flat

(** @canonical Gsl.Version *)
module Version = Gsl__Version

(** @canonical Gsl.Wavelet *)
module Wavelet = Gsl__Wavelet
